- hosts: localhost
  connection: local
  gather_facts: no
  become: no
  vars_files:
      - "{{ vars_file }}"
  roles:
      # Group systems
      - instance-groups
      
- hosts: localhost
  connection: local
  gather_facts: no
  become: no
  vars_files:
      - "{{ vars_file }}"
  roles:
      - host-up
      
- hosts: cluster_hosts
  gather_facts: yes 
  become: yes
  serial: 1
  user: ec2-user
  vars_files:
      - "{{ vars_file }}"
  roles:
      - rhsm-subscription
      
- hosts: cluster_hosts
  gather_facts: no
  become: yes
  user: ec2-user
  vars_files:
      - "{{ vars_file }}"
  roles:
      - rhsm-repos
      - prerequisites
      
- include: openshift-setup.yaml

- hosts: localhost
  connection: local
  gather_facts: yes
  become: no
  vars_files:
      - "{{ vars_file }}"
  roles:
      - s3-registry-bucket
      
- hosts: schedulable_nodes
  gather_facts: no
  become: yes
  vars_files:
      - "{{ vars_file }}"
  roles:
      - openshift-emptydir-quota

- hosts: localhost
  connection: local
  gather_facts: yes
  become: no
  vars_files:
      - "{{ vars_file }}"
  roles:
      - cfn-outputs

- hosts: primary_master
  gather_facts: no
  become: yes
  vars_files:
      - "{{ vars_file }}"
  roles:
      - openshift-registry
