---
- name: Create Azure Resource Group
  shell: azure group create "{{ stack_name }}" "{{ region }}"
  when: create=true
  
- name: Create local parameters_file:
  hosts: localhost
  template:
    src: playbooks/roles/arm-deploy/files/parameters.json.j2
    dest: rendered/parameters.json

- name: Deploy Azure Template to Resource Group
  shell: azure group deployment create -g "{{ stack_name }}" -n "{{ stack_name }}" -f "{{ playbooks/roles/arm-deploy/files/new.json }}" -p rendered/parameters.json -v
